### ISSUE TITLE
Change default browser for preview

### ISSUE THREAD

**Issue by mixolydianmel** [weirongxu/coc-webview#1]
Not sure if this feature exists yet, but if there is a way to change the default browser used for previewing the markdown I haven't found it in any of the documentation.

Is this possible?

**Comment by weirongxu** [comment]
I will support the use of the command method to specify the browser, instead of the default open feature

**Comment by mixolydianmel** [comment]
Thanks! Also apologies for putting this issue in the wrong place, was unaware this was the actual thing in need of modification.

**Comment by weirongxu** [comment]
Check out the `webview.openCommand`
